dataset:
    dummy_variables:
        - "season"
        - "weathersit"
        - "mnth"
        - "hr"
        - "weekday"
    fields_to_drop:
        - "instant"
        - "dteday"
        - "season"
        - "weathersit"
        - "weekday"
        - "atemp"
        - "mnth"
        - "workingday"
        - "hr"
    quant_features:
        - "casual"
        - "registered"
        - "cnt"
        - "temp"
        - "hum"
        - "windspeed"
    target_fields:
        - "cnt"
        - "casual"
        - "registered"
hyperparameters:
    iterations: 3000
    learning_rate: 1
    hidden_nodes: 10
    output_nodes: 1
dataset_link: "data/hour.csv"